server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

# üîç JOB 1: Logs de RED (Suricata)
  - job_name: suricata
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          # Busca el archivo JSON (mejor para Grafana) o el fast.log
          __path__: /var/log/suricata/*.json 

# üõ°Ô∏è JOB 2: Logs de WEB (WAF ModSecurity)
  - job_name: waf
    static_configs:
      - targets:
          - localhost
        labels:
          job: modsecurity
          # El archivo donde ModSecurity escribe los bloqueos
          __path__: /var/log/modsec/modsec_audit.log
