server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://soc-loki:3100/loki/api/v1/push

scrape_configs:
  # Suricata Logs
  - job_name: suricata
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          __path__: /var/log/suricata/eve.json

  # Zeek Logs (NUEVO)
  - job_name: zeek
    static_configs:
      - targets:
          - localhost
        labels:
          job: zeek
          __path__: /var/log/zeek/*.log
